version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notespace-web-prod
    ports:
      - "2503:2503" # Exposing the production Node.js port
    environment:
      - NODE_ENV=production
      - PORT=2503
    restart: unless-stopped
