version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notespace-web-prod
    ports:
      - "3000:3000" # Exposing the production Node.js port
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
