version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notespace-web
    ports:
      - "5173:5173" # Vite default port
    volumes:
      - .:/app
      - /app/node_modules # Prevents local node_modules from overriding container's
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # Helps with hot-reloading on certain OS/Docker setups
    command: npm run dev -- --host
